# Configuration for the Travis CI build system.
# Yes, this configuration is pretty primitive in its current form.

language: c

os: linux

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libreadline-dev

script:
- chmod 755 scripts/detect-os.sh scripts/detect-proc.sh
- make dep && make && make check

