# Configuration for the Travis CI build system.
# Yes, this configuration is pretty primitive in its current form.

language: c

os: linux

compiler: gcc

addons:
  apt:
    sources:
      - libreadline-dev

script: make dep && make && make check

